# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 16:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20160508_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='action',
        ),
    ]
