# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_auto_20160425_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='abc', unique=True),
        ),
    ]
