# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_auto_20160426_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='share_message',
            field=models.TextField(default='\nCheck out this awesome video. \n'),
        ),
    ]
