# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0010_taggeditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taggeditem',
            name='tag',
            field=models.SlugField(choices=[('python', 'python'), ('django', 'django'), ('css', 'css'), ('bootsrap', 'bootstrap')]),
        ),
    ]
