# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 14:03
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_end', models.DateTimeField(default=datetime.datetime(2016, 5, 17, 14, 3, 5, 655718, tzinfo=utc))),
                ('date_start', models.DateTimeField(default=datetime.datetime(2016, 5, 17, 14, 3, 5, 655831, tzinfo=utc))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
