# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 01:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageview',
            name='timestamp',
            field=models.DateField(default=datetime.datetime(2016, 5, 16, 1, 29, 57, 267453, tzinfo=utc)),
        ),
    ]
