# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 14:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_auto_20160516_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageview',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 16, 14, 26, 11, 25847, tzinfo=utc)),
        ),
    ]
