# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 14:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_auto_20160516_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageview',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 17, 14, 3, 5, 682327, tzinfo=utc)),
        ),
    ]
